> Try catch trong swift k·∫øt h·ª£p v·ªõi throwing l·ªói gi√∫p b·∫°n c√≥ th·ªÉ x·ª≠ l√Ω t·ªët b·∫•t k·ª≥ l·ªói n√†o trong code c·ªßa m√¨nh. M·ªôt ph∆∞∆°ng th·ª©c c√≥ th·ªÉ ƒë∆∞·ª£c ƒë·ªãnh nghƒ©a l√† throwing, v·ªÅ c∆° b·∫£n c√≥ nghƒ©a l√† n·∫øu c√≥ g√¨ sai, n√≥ c√≥ th·ªÉ th√¥ng b√°o c√≥ l·ªói ƒë√£ x·∫£y ra. ƒê·ªÉ b·∫Øt l·ªói n√†y, ch√∫ng ta c·∫ßn tri·ªÉn khai m·ªôt c√¢u l·ªánh g·ªçi l√† do-catch.
Kh√¥ng ph·∫£i l√∫c n√†o c≈©ng b·∫Øt bu·ªôc ph·∫£i s·ª≠ d·ª•ng c√¢u l·ªánh do-catch v·ªõi method throwing. H√£y  c√πng t√¨m hi·ªÉu s√¢u h∆°n v·ªÅ ch√∫ng. 

### 1. T·∫°o method throwing b·∫±ng c√°ch s·ª≠ d·ª•ng t·ª´ kh√≥a throws 

T·∫°o m·ªôt method throwing b·∫±ng c√°ch th√™m t·ª´ kh√≥a throws v√†o m·ªôt method ngay tr∆∞·ªõc c√¢u l·ªánh return.
Trong v√≠ d·ª• n√†y, ch√∫ng t√¥i s·ª≠ d·ª•ng m·ªôt method ƒë·ªÉ c·∫≠p nh·∫≠t t√™n cho ng∆∞·ªùi d√πng c·ªßa m·ªôt ng∆∞·ªùi d√πng c√≥ ƒë·ªãnh danh c·ª• th·ªÉ.

```
func update(name: String, forUserIdentifier userIdentifier: String) {
    // This method is not throwing any errors
}

func update(name: String, forUserIdentifier userIdentifier: String) throws {
    // The throws keyword makes that this method c√°n throw an error
}
```

Khi g·ªçi m·ªôt method throwing, b·∫°n c√≥ th·ªÉ g·∫∑p l·ªói sau:
```
Call can throw but is not marked with ‚Äòtry‚Äô
```

ƒêi·ªÅu n√†y c√≥ nghƒ©a l√† b·∫°n ph·∫£i s·ª≠ d·ª•ng t·ª´ kh√≥a try tr∆∞·ªõc m·ªôt ƒëo·∫°n code c√≥ th·ªÉ g√¢y ra l·ªói.

```
try update(name: "Antoine Eval", forUserIdentifier: "VALKY2412")
```

### 2. Throwing initializer trong Swift

M·ªôt ƒëi·ªÅu tuy·ªát v·ªùi l√† b·∫°n c≈©ng c√≥ th·ªÉ t·∫°o m·ªôt tr√¨nh kh·ªüi t·∫°o **Throwing**. ƒêi·ªÅu n√†y ƒë·∫∑c bi·ªát h·ªØu √≠ch khi b·∫°n mu·ªën x√°c th·ª±c c√°c thu·ªôc t√≠nh ƒë·ªÉ kh·ªüi t·∫°o m·ªôt ƒë·ªëi t∆∞·ª£ng nh·∫•t ƒë·ªãnh. V√≠ d·ª•: b·∫°n c√≥ th·ªÉ mu·ªën x√°c th·ª±c t√™n ng∆∞·ªùi d√πng tr∆∞·ªõc khi t·∫°o ƒë·ªëi t∆∞·ª£ng *User*.

```
struct User {
    enum ValidationError: Error {
        case emptyName
        case nameToShort(nameLength: Int)
    }

    let name: String

    init(name: String) throws {
        guard !name.isEmpty else {
            throw ValidationError.emptyName
        }
        guard name.count > 2 else {
            throw ValidationError.nameToShort(nameLength: name.count)
        }

        self.name = name
    }
}

let user = try User(name: "Antoine Eval")
```

### 3. X·ª≠ l√Ω l·ªói trong Swift b·∫±ng c√¢u l·ªánh do-catch

ƒê·ªÉ b·∫Øt l·ªói trong Swift, ch√∫ng ta c·∫ßn s·ª≠ d·ª•ng c√¢u l·ªánh do-catch. V√≠ d·ª• sau s·ª≠ d·ª•ng c√° th·ªÉ User ƒë∆∞·ª£c x√°c ƒë·ªãnh tr∆∞·ªõc ƒë√≥.

```
do {
    let user = try User(name: "")
    print("Created user with name \(user.name)")
} catch {
    print("User creation failed with error: \(error)")
}

// Prints: User creation failed with error: emptyName
```

L·ªói emptyName ƒë∆∞·ª£c ƒë∆∞a ra do t√™n ng∆∞·ªùi d√πng ƒë∆∞·ª£c cung c·∫•p tr·ªëng. K·∫øt qu·∫£ l√† kh·ªëi catch ƒë∆∞·ª£c g·ªçi. Nh∆∞ b·∫°n th·∫•y, ch√∫ng ta c√≥ th·ªÉ s·ª≠ d·ª•ng thu·ªôc t√≠nh l·ªói c·ª•c b·ªô ƒë·ªÉ in ra l·ªói ƒë√£ m·∫Øc. Kh·ªëi b·∫Øt ch·ªâ ƒë∆∞·ª£c g·ªçi khi x·∫£y ra l·ªói.

### 4. Catching m·ªôt lo·∫°i l·ªói c·ª• th·ªÉ

V√¨ ch√∫ng ta kh√¥ng th·ªÉ ch·ªâ ƒë·ªãnh lo·∫°i l·ªói s·∫Ω ƒë∆∞·ª£c th√¥ng b√°o b·ªüi m·ªôt method, ch√∫ng ta ph·∫£i t√≠nh ƒë·∫øn c√°c lo·∫°i l·ªói kh√°c nhau c√≥ th·ªÉ ƒë∆∞·ª£c t·∫°o ra. Do ƒë√≥, b·∫°n mu·ªën b·∫Øt v√† x·ª≠ l√Ω c√°c lo·∫°i l·ªói c·ª• th·ªÉ trong m·ªôt c√¢u l·ªánh catch ri√™ng. 

Trong v√≠ d·ª• sau, ch√∫ng ta ƒë√£ tri·ªÉn khai method c·∫≠p nh·∫≠t t√™n. Method n√†y hi·ªán c√≥ th·ªÉ throw c·∫£ l·ªói x√°c th·ª±c ng∆∞·ªùi d√πng v√† l·ªói c∆° s·ªü d·ªØ li·ªáu ƒë∆∞·ª£c tr·∫£ ra t·ª´ method `fetchUser`.

```
func fetchUser(for identifier: String) throws -> User {
    // Fetches the user from the database
}

func update(name: String, forUserIdentifier userIdentifier: String) throws {
    guard !name.isEmpty else {
        throw User.ValidationError.emptyName
    }
    var user = try fetchUser(for: userIdentifier)
    user.update(name)
    user.save()
}
```

S·∫Ω r·∫•t tuy·ªát n·∫øu b·∫°n b·∫Øt ƒë∆∞·ª£c l·ªói trong c√°c kh·ªëi ƒë∆∞·ª£c t√°ch bi·ªát ƒë·ªÉ hi·ªÉn th·ªã m·ªôt c·∫£nh b√°o kh√°c n·∫øu ch·ªâ m·ªói t√™n kh√¥ng h·ª£p l·ªá. C√≥ m·ªôt s·ªë c√°ch ƒë·ªÉ l√†m ƒëi·ªÅu n√†y:

```
do {
    try update(name: "Antoine Eval", forUserIdentifier: "VALKY2412")
} catch User.ValidationError.emptyName {
    // Called only when the `User.ValidationError.emptyName` error is thrown
} catch User.ValidationError.nameToShort(let nameLength) where nameLength == 1 {
    // Only when the `nameToShort` error is thrown for an input of 1 character
} catch is User.ValidationError {
    // All `User.ValidationError` types except for the earlier catch `emptyName` error.
} catch {
    // All other errors
}
```

C√≥ 1 s·ªë ƒëi·ªÅu c·∫ßn l√†m r√µ ·ªü ƒë√¢y:

* Th·ª© t·ª± catching l√† quan tr·ªçng. Trong v√≠ d·ª• n√†y, ƒë·∫ßu ti√™n ch√∫ng ta catch c·ª• th·ªÉ l√† emptyName, sau ƒë√≥ l√† t·∫•t c·∫£ c√°c User.ValidationError kh√°c. N·∫øu ch√∫ng ta ho√°n ƒë·ªïi hai th·ª© t·ª± n√†y, l·ªánh b·∫Øt emptyName c·ª• th·ªÉ s·∫Ω kh√¥ng bao gi·ªù ƒë∆∞·ª£c g·ªçi.

* `where` c√≥ th·ªÉ ƒë∆∞·ª£c s·ª≠ d·ª•ng ƒë·ªÉ l·ªçc c√°c gi√° tr·ªã l·ªói. Trong v√≠ d·ª• n√†y, ch√∫ng ta ch·ªâ th√≠ch b·∫Øt c√°c ƒë·∫ßu v√†o t√™n c√≥ ƒë·ªô d√†i c·ª• th·ªÉ l√† 1 k√Ω t·ª±.

* S·ª≠ d·ª•ng t·ª´ kho√° `is` ch√∫ng ta c√≥ th·ªÉ b·∫Øt l·ªói c·ªßa m·ªôt lo·∫°i c·ª• th·ªÉ.

* Vi·ªác ƒë√≥ng b·∫Øt cu·ªëi c√πng s·∫Ω b·∫Øt t·∫•t c·∫£ c√°c l·ªói kh√°c.

C≈©ng c√≥ nh·ªØng tr∆∞·ªùng h·ª£p m√† b·∫°n g·∫∑p hai ho·∫∑c nhi·ªÅu lo·∫°i l·ªói c·ª• th·ªÉ. Trong tr∆∞·ªùng h·ª£p n√†y, b·∫°n c√≥ th·ªÉ s·ª≠ d·ª•ng danh s√°ch trong c√¢u l·ªánh catch c·ªßa m√¨nh:

```
do {
    try update(name: "Antoine Eval", forUserIdentifier: "VALKY2412")
} catch User.ValidationError.emptyName, User.ValidationError.nameToShort {
    // Only called for `emptyName` and `nameToShort`
} catch {
    // All other errors
}
```

L∆∞u √Ω ·ªü ƒë√¢y r·∫±ng ch√∫ng ta ƒë√£ lo·∫°i b·ªè paramater nameToShort. ƒê√¢y l√† ƒëi·ªÅu b·∫°n lu√¥n c√≥ th·ªÉ l√†m khi l√†m vi·ªác v·ªõi enums n·∫øu b·∫°n kh√¥ng quan t√¢m ƒë·∫øn gi√° tr·ªã ƒë∆∞·ª£c li√™n k·∫øt.

### 5. S·ª≠ d·ª•ng try? v·ªõi m·ªôt method throwing

N·∫øu b·∫°n kh√¥ng quan t√¢m ƒë·∫øn vi·ªác ph√°t hi·ªán b·∫•t k·ª≥ l·ªói n√†o, b·∫°n c≈©ng c√≥ th·ªÉ quy·∫øt ƒë·ªãnh s·ª≠ d·ª•ng `try?`. D·∫•u ch·∫•m h·ªèi ƒë·∫±ng sau t·ª´ kh√≥a `try` v·ªÅ c∆° b·∫£n cho bi·∫øt r·∫±ng ch√∫ng ta kh√¥ng quan t√¢m ƒë·∫øn l·ªói c√≥ th·ªÉ x·∫£y ra.

```
let user = try? User(name: "")
print(user?.name) // Prints "nil" if an error occurred upon init.
```

Gi√° tr·ªã s·∫Ω l√† m·ªôt c√° th·ªÉ User t√πy ch·ªçn ho·∫∑c nil v√† l·ªói ƒë∆∞·ª£c ƒë∆∞a ra ho√†n to√†n b·ªã b·ªè qua.

### 6. S·ª≠ d·ª•ng try! v·ªõi m·ªôt method throwing

N·∫øu b·∫°n mu·ªën ·ª©ng d·ª•ng c·ªßa m√¨nh kh√¥ng th√†nh c√¥ng ngay l·∫≠p t·ª©c, b·∫°n c√≥ th·ªÉ d√πng `try!` v·ªõi method throwing. V·ªÅ c∆° b·∫£n, ƒëi·ªÅu n√†y s·∫Ω l√†m ·ª©ng d·ª•ng c·ªßa b·∫°n b·ªã l·ªói gi·ªëng nh∆∞ m·ªôt th√¥ng b√°o l·ªói nghi√™m tr·ªçng.

```
let user = try! User(name: "")
print(user.name)
```

ƒêi·ªÅu n√†y s·∫Ω d·∫´n ƒë·∫øn l·ªói sau v√¨ ƒë·∫ßu v√†o t√™n tr·ªëng:

```
Fatal error: ‚Äòtry!‚Äô expression unexpectedly raised an error: User.ValidationError.emptyName
```

### 7. K·∫øt lu·∫≠n

Error handling trong Swift r·∫•t t·ªët. N√≥ cho ph√©p b·∫°n vi·∫øt code c√≥ th·ªÉ ƒë·ªçc ƒë∆∞·ª£c ƒë·ªìng th·ªùi x·ª≠ l√Ω nh·ªØng lu·ªìng kh√¥ng h√†i l√≤ng. B·∫±ng c√°ch c√≥ th·ªÉ b·∫Øt c√°c lo·∫°i l·ªói c·ª• th·ªÉ ho·∫∑c s·ª≠ d·ª•ng t·ª´ kh√≥a `where`, ch√∫ng ta c√≥ th·ªÉ linh ho·∫°t x·ª≠ l√Ω c√°c t√¨nh hu·ªëng c·ª• th·ªÉ n·∫øu c·∫ßn. 

V·∫≠y l√† b√†i vi·∫øt c·ªßa m√¨nh ƒë·∫øn ƒë√¢y l√† h·∫øt üòÅ. Hy v·ªçng r·∫±ng, ƒëi·ªÅu n√†y s·∫Ω gi√∫p b·∫°n trong vi·ªác code hi·ªáu qu·∫£ h∆°n.

C·∫£m ∆°n c√°c b·∫°n ƒë√£ theo d√µi b√†i vi·∫øt. üòÉ